import type { Metadata } from "next";
import "./globals.css";
import TopNav from "@/Components/TopNav/TopNav";
import NavBar from "@/Components/NavBar/NavBar";

export const metadata: Metadata = {
  title: "Be-strong",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className="container">
          <TopNav />
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
